name = "AllTools"
uuid = "363e5ecb-0803-4ac0-baed-08dfa3a41905"
authors = ["Tsung-Hsi Wu <okatsn@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.6.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
